// Generated by scripts/gen-abi.mjs — do not edit by hand.
//
// Regenerate with `npm run abi:gen` after any contract change, and commit the result: this file
// is the only copy of the ABI that exists inside frontend/, which is all a Vercel build can see.
//
// Unlike the hand-written ABI this replaced, it carries the contracts' `error` entries, so viem
// can decode custom reverts structurally instead of regexing them out of message strings.

import type { Abi } from "viem";

export const megaPotAbi = [
  {
    "type": "error",
    "name": "AlreadyClaimed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyCompactedThisRound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AmountTooLarge",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AssetMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BudgetExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BufferFull",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DepositsPaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientPrincipal",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAllocation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidKMSSignatures",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MegapotRouteNotSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoPrize",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoTickets",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoYield",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingToInvest",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OnlyKeeper",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PreviousRoundLive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SenderNotAllowedToUseHandle",
    "inputs": [
      {
        "name": "handle",
        "type": "bytes32"
      },
      {
        "name": "sender",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownTrack",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnsupportedToken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongState",
    "inputs": []
  },
  {
    "type": "error",
    "name": "YieldSourceAlreadySet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "YieldSourceNotSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZamaProtocolUnsupported",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmountFunded",
    "inputs": []
  },
  {
    "type": "event",
    "name": "BridgedToMegapot",
    "anonymous": false,
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "BufferRefilled",
    "anonymous": false,
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "BufferTargetSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "target",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Claimed",
    "anonymous": false,
    "inputs": [
      {
        "name": "track",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "roundId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "user",
        "type": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "ConfigUpdated",
    "anonymous": false,
    "inputs": []
  },
  {
    "type": "event",
    "name": "DeployRequested",
    "anonymous": false,
    "inputs": [
      {
        "name": "unwrapRequestId",
        "type": "bytes32",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "Deposited",
    "anonymous": false,
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true
      },
      {
        "name": "rangeIndex",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Drawn",
    "anonymous": false,
    "inputs": [
      {
        "name": "track",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "roundId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "prize",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "totalTickets",
        "type": "uint64",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "EntriesClosed",
    "anonymous": false,
    "inputs": [
      {
        "name": "track",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "roundId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "cursorSnapshot",
        "type": "bytes32",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "EntriesFinalized",
    "anonymous": false,
    "inputs": [
      {
        "name": "track",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "roundId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "totalTickets",
        "type": "uint64",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Harvested",
    "anonymous": false,
    "inputs": [
      {
        "name": "surplus",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "toPrize",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "toTickets",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Invested",
    "anonymous": false,
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "KeeperSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "keeper",
        "type": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "MegapotAllocationSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true
      },
      {
        "name": "bps",
        "type": "uint16",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "MegapotRouteSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "bridge",
        "type": "address",
        "indexed": false
      },
      {
        "name": "domain",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "agent",
        "type": "bytes32",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "anonymous": false,
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "PrizeFunded",
    "anonymous": false,
    "inputs": [
      {
        "name": "track",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "minted",
        "type": "uint64",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "PublicDecryptionVerified",
    "anonymous": false,
    "inputs": [
      {
        "name": "handlesList",
        "type": "bytes32[]",
        "indexed": false
      },
      {
        "name": "abiEncodedCleartexts",
        "type": "bytes",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Restaked",
    "anonymous": false,
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "RoundStarted",
    "anonymous": false,
    "inputs": [
      {
        "name": "track",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "roundId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "drawTime",
        "type": "uint64",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "SplitSkipped",
    "anonymous": false,
    "inputs": [
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "SweepRequested",
    "anonymous": false,
    "inputs": [
      {
        "name": "track",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "roundId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "unclaimed",
        "type": "bytes32",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Swept",
    "anonymous": false,
    "inputs": [
      {
        "name": "track",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "roundId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "rolledOver",
        "type": "uint64",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "TicketBudgetFunded",
    "anonymous": false,
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "anonymous": false,
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "YieldSourceSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "yieldSource",
        "type": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "function",
    "name": "ALLOCATION_STEP",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16"
      }
    ]
  },
  {
    "type": "function",
    "name": "MAIN",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "function",
    "name": "MAX_AUTOCLAIM",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "MAX_RANGES",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "MEGA",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "function",
    "name": "asset",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "awardOf",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint256"
      },
      {
        "name": "user",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "bridge",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "bridgeToMegapot",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "maxFee",
        "type": "uint256"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "bufferStatus",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "buffered",
        "type": "uint256"
      },
      {
        "name": "target",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "bufferTarget",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "cToken",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "canCompact",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "user",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "claim",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "closeEntries",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "confidentialBalanceOf",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "user",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialProtocolId",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "cursor",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "deployedPrincipal",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "deposit",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "encAmount",
        "type": "bytes32"
      },
      {
        "name": "proof",
        "type": "bytes"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "depositsPaused",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "draw",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint256"
      },
      {
        "name": "claimWindow",
        "type": "uint64"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "emergencyUnwind",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": []
  },
  {
    "type": "function",
    "name": "entryRound",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "finalizeEntries",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint256"
      },
      {
        "name": "totalTickets",
        "type": "uint64"
      },
      {
        "name": "decryptionProof",
        "type": "bytes"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "finalizeSweep",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint256"
      },
      {
        "name": "unclaimedAmount",
        "type": "uint64"
      },
      {
        "name": "decryptionProof",
        "type": "bytes"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "fundPrize",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "minted",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "fundTicketBudget",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "getRound",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "drawTime",
            "type": "uint64"
          },
          {
            "name": "claimDeadline",
            "type": "uint64"
          },
          {
            "name": "totalTickets",
            "type": "uint64"
          },
          {
            "name": "prize",
            "type": "uint64"
          },
          {
            "name": "state",
            "type": "uint8"
          },
          {
            "name": "cursorSnapshot",
            "type": "bytes32"
          },
          {
            "name": "ticket",
            "type": "bytes32"
          },
          {
            "name": "unclaimed",
            "type": "bytes32"
          }
        ]
      }
    ]
  },
  {
    "type": "function",
    "name": "harvest",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": [
      {
        "name": "surplus",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "hasClaimed",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "",
        "type": "uint8"
      },
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "invest",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "keeper",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "lastWithdrawnOf",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "user",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "megapotBps",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16"
      }
    ]
  },
  {
    "type": "function",
    "name": "megapotDomain",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ]
  },
  {
    "type": "function",
    "name": "megapotShareBps",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16"
      }
    ]
  },
  {
    "type": "function",
    "name": "owner",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "pendingDeploy",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "playsMegapot",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "user",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "prizeReserve",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "rangeCountOf",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "user",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "rangesOf",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "user",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "components": [
          {
            "name": "lower",
            "type": "bytes32"
          },
          {
            "name": "upper",
            "type": "bytes32"
          },
          {
            "name": "round",
            "type": "uint64"
          }
        ]
      }
    ]
  },
  {
    "type": "function",
    "name": "refillBuffer",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": []
  },
  {
    "type": "function",
    "name": "requestDeploy",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": [
      {
        "name": "unwrapRequestId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "requestSweep",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "restake",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": []
  },
  {
    "type": "function",
    "name": "roundsLength",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "setBufferTarget",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "target",
        "type": "uint256"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "setDepositsPaused",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "paused",
        "type": "bool"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "setKeeper",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "keeper_",
        "type": "address"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "setMegapotAllocation",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "bps",
        "type": "uint16"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "setMegapotRoute",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "bridge_",
        "type": "address"
      },
      {
        "name": "domain",
        "type": "uint32"
      },
      {
        "name": "agent",
        "type": "address"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "setSplitMaxSkew",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "skew",
        "type": "uint64"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "setYieldSource",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "source",
        "type": "address"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "settledTickets",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "splitMaxSkew",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "function",
    "name": "startRound",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      },
      {
        "name": "drawTime",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "roundId",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "ticketAgent",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "ticketBudget",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "topUpBuffer",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": [
      {
        "name": "pulled",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "trackInfo",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "track",
        "type": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "entryRound_",
        "type": "uint64"
      },
      {
        "name": "settledTickets_",
        "type": "uint64"
      },
      {
        "name": "prizeReserve_",
        "type": "uint64"
      },
      {
        "name": "rounds_",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "withdraw",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "encAmount",
        "type": "bytes32"
      },
      {
        "name": "proof",
        "type": "bytes"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "yieldSource",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  }
] as const satisfies Abi;

export const prizeInboxAbi = [
  {
    "type": "error",
    "name": "NothingToFlush",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "event",
    "name": "Flushed",
    "anonymous": false,
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "function",
    "name": "asset",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "flush",
    "stateMutability": "nonpayable",
    "inputs": [],
    "outputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "pending",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "pot",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  }
] as const satisfies Abi;

export const confidentialUsdcAbi = [
  {
    "type": "error",
    "name": "ERC7984InvalidReceiver",
    "inputs": [
      {
        "name": "receiver",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC7984InvalidSender",
    "inputs": [
      {
        "name": "sender",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC7984TotalSupplyOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ERC7984UnauthorizedCaller",
    "inputs": [
      {
        "name": "caller",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC7984UnauthorizedSpender",
    "inputs": [
      {
        "name": "holder",
        "type": "address"
      },
      {
        "name": "spender",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC7984UnauthorizedUseOfEncryptedAmount",
    "inputs": [
      {
        "name": "amount",
        "type": "bytes32"
      },
      {
        "name": "user",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidKMSSignatures",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidUnwrapRequest",
    "inputs": [
      {
        "name": "unwrapRequestId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintDowncast",
    "inputs": [
      {
        "name": "bits",
        "type": "uint8"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SenderNotAllowedToUseHandle",
    "inputs": [
      {
        "name": "handle",
        "type": "bytes32"
      },
      {
        "name": "sender",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZamaProtocolUnsupported",
    "inputs": []
  },
  {
    "type": "event",
    "name": "AmountDiscloseRequested",
    "anonymous": false,
    "inputs": [
      {
        "name": "encryptedAmount",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "requester",
        "type": "address",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "AmountDisclosed",
    "anonymous": false,
    "inputs": [
      {
        "name": "encryptedAmount",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint64",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "ConfidentialTransfer",
    "anonymous": false,
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "bytes32",
        "indexed": true
      }
    ]
  },
  {
    "type": "event",
    "name": "OperatorSet",
    "anonymous": false,
    "inputs": [
      {
        "name": "holder",
        "type": "address",
        "indexed": true
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "until",
        "type": "uint48",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "PublicDecryptionVerified",
    "anonymous": false,
    "inputs": [
      {
        "name": "handlesList",
        "type": "bytes32[]",
        "indexed": false
      },
      {
        "name": "abiEncodedCleartexts",
        "type": "bytes",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "UnwrapFinalized",
    "anonymous": false,
    "inputs": [
      {
        "name": "receiver",
        "type": "address",
        "indexed": true
      },
      {
        "name": "unwrapRequestId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "encryptedAmount",
        "type": "bytes32",
        "indexed": false
      },
      {
        "name": "cleartextAmount",
        "type": "uint64",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "UnwrapRequested",
    "anonymous": false,
    "inputs": [
      {
        "name": "receiver",
        "type": "address",
        "indexed": true
      },
      {
        "name": "unwrapRequestId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "bytes32",
        "indexed": false
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialBalanceOf",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialProtocolId",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTotalSupply",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTransfer",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "name": "inputProof",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTransfer",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTransferAndCall",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "bytes32"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTransferAndCall",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "name": "inputProof",
        "type": "bytes"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTransferFrom",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "name": "inputProof",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTransferFrom",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTransferFromAndCall",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "name": "inputProof",
        "type": "bytes"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "confidentialTransferFromAndCall",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "bytes32"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "contractURI",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ]
  },
  {
    "type": "function",
    "name": "decimals",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "function",
    "name": "discloseEncryptedAmount",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "name": "cleartextAmount",
        "type": "uint64"
      },
      {
        "name": "decryptionProof",
        "type": "bytes"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "finalizeUnwrap",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "unwrapRequestId",
        "type": "bytes32"
      },
      {
        "name": "unwrapAmountCleartext",
        "type": "uint64"
      },
      {
        "name": "decryptionProof",
        "type": "bytes"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "inferredTotalSupply",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "isOperator",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "holder",
        "type": "address"
      },
      {
        "name": "spender",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "maxTotalSupply",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "name",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ]
  },
  {
    "type": "function",
    "name": "onTransferReceived",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes4"
      }
    ]
  },
  {
    "type": "function",
    "name": "rate",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "requestDiscloseEncryptedAmount",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "encryptedAmount",
        "type": "bytes32"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "setOperator",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "operator",
        "type": "address"
      },
      {
        "name": "until",
        "type": "uint48"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "symbol",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ]
  },
  {
    "type": "function",
    "name": "underlying",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "unwrap",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "name": "inputProof",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "unwrap",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "unwrapAmount",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "unwrapRequestId",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "unwrapRequester",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "unwrapRequestId",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "wrap",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "function",
    "name": "wrapAndAuthorize",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "operator",
        "type": "address"
      },
      {
        "name": "until",
        "type": "uint48"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "wrapWithPermit",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "operator",
        "type": "address"
      },
      {
        "name": "until",
        "type": "uint48"
      },
      {
        "name": "deadline",
        "type": "uint256"
      },
      {
        "name": "v",
        "type": "uint8"
      },
      {
        "name": "r",
        "type": "bytes32"
      },
      {
        "name": "s",
        "type": "bytes32"
      }
    ],
    "outputs": []
  }
] as const satisfies Abi;

export const yieldVaultAbi = [
  {
    "type": "error",
    "name": "ERC20InsufficientAllowance",
    "inputs": [
      {
        "name": "spender",
        "type": "address"
      },
      {
        "name": "allowance",
        "type": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InsufficientBalance",
    "inputs": [
      {
        "name": "sender",
        "type": "address"
      },
      {
        "name": "balance",
        "type": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidApprover",
    "inputs": [
      {
        "name": "approver",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidReceiver",
    "inputs": [
      {
        "name": "receiver",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidSender",
    "inputs": [
      {
        "name": "sender",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC20InvalidSpender",
    "inputs": [
      {
        "name": "spender",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC4626ExceededMaxDeposit",
    "inputs": [
      {
        "name": "receiver",
        "type": "address"
      },
      {
        "name": "assets",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC4626ExceededMaxMint",
    "inputs": [
      {
        "name": "receiver",
        "type": "address"
      },
      {
        "name": "shares",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC4626ExceededMaxRedeem",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      },
      {
        "name": "shares",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC4626ExceededMaxWithdraw",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      },
      {
        "name": "assets",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "event",
    "name": "Approval",
    "anonymous": false,
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "spender",
        "type": "address",
        "indexed": true
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Deposit",
    "anonymous": false,
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "indexed": true
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "assets",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "shares",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Transfer",
    "anonymous": false,
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "event",
    "name": "Withdraw",
    "anonymous": false,
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "indexed": true
      },
      {
        "name": "receiver",
        "type": "address",
        "indexed": true
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "assets",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "shares",
        "type": "uint256",
        "indexed": false
      }
    ]
  },
  {
    "type": "function",
    "name": "allowance",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      },
      {
        "name": "spender",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "approve",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "spender",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "asset",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ]
  },
  {
    "type": "function",
    "name": "balanceOf",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "convertToAssets",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "shares",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "convertToShares",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "assets",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "decimals",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "function",
    "name": "deposit",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "assets",
        "type": "uint256"
      },
      {
        "name": "receiver",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "maxDeposit",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "maxMint",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "maxRedeem",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "maxWithdraw",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "mint",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "shares",
        "type": "uint256"
      },
      {
        "name": "receiver",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "name",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ]
  },
  {
    "type": "function",
    "name": "previewDeposit",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "assets",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "previewMint",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "shares",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "previewRedeem",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "shares",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "previewWithdraw",
    "stateMutability": "view",
    "inputs": [
      {
        "name": "assets",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "redeem",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "shares",
        "type": "uint256"
      },
      {
        "name": "receiver",
        "type": "address"
      },
      {
        "name": "owner",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "setWithdrawCap",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "cap",
        "type": "uint256"
      }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "symbol",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ]
  },
  {
    "type": "function",
    "name": "totalAssets",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "totalSupply",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "transfer",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "transferFrom",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ]
  },
  {
    "type": "function",
    "name": "withdraw",
    "stateMutability": "nonpayable",
    "inputs": [
      {
        "name": "assets",
        "type": "uint256"
      },
      {
        "name": "receiver",
        "type": "address"
      },
      {
        "name": "owner",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "function",
    "name": "withdrawCap",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ]
  }
] as const satisfies Abi;
