#!/usr/bin/env node
/**
 * Generate `lib/abi/generated.ts` from the compiled Hardhat artifacts.
 *
 * The ABI used to be maintained by hand, which is how it drifted 13 functions behind the contract
 * without anything noticing. It cannot be *imported* from the artifacts either, for three separate
 * reasons, each sufficient on its own:
 *
 *   1. `artifacts/` is gitignored, so a Vercel checkout has no such file.
 *   2. Vercel's root directory is `frontend/`, so nothing above it exists at build time.
 *   3. A JSON import loses `as const`, and that const assertion is the only reason wagmi can infer
 *      return types across `lib/usePool.ts`.
 *
 * So: generate, and commit the result. Run `npm run abi:gen` after any contract change;
 * `npm run abi:check` fails if the committed file is stale, and `scripts/preflight.mjs` separately
 * checks that the *deployed* bytecode still answers it.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");

const SOURCES = [
  { name: "megaPotAbi", path: "artifacts/contracts/MegaPot.sol/MegaPot.json" },
  { name: "prizeInboxAbi", path: "artifacts/contracts/PrizeInbox.sol/PrizeInbox.json" },
  { name: "confidentialUsdcAbi", path: "artifacts/contracts/token/ConfidentialUSDC.sol/ConfidentialUSDC.json" },
  { name: "yieldVaultAbi", path: "artifacts/contracts/mocks/MockYieldVault.sol/MockYieldVault.json" },
];

/** Drop the pieces of an artifact entry the browser never needs. */
function slim(entry) {
  const out = { type: entry.type };
  if (entry.name) out.name = entry.name;
  if (entry.stateMutability) out.stateMutability = entry.stateMutability;
  if (entry.anonymous !== undefined) out.anonymous = entry.anonymous;
  if (entry.inputs) out.inputs = entry.inputs.map(slimParam);
  if (entry.outputs) out.outputs = entry.outputs.map(slimParam);
  return out;
}

function slimParam(p) {
  const out = { name: p.name ?? "", type: p.type };
  if (p.indexed !== undefined) out.indexed = p.indexed;
  if (p.components) out.components = p.components.map(slimParam);
  return out;
}

const blocks = SOURCES.map(({ name, path }) => {
  const artifact = JSON.parse(readFileSync(join(repo, path), "utf8"));
  // Constructors carry no selector and nothing in the app calls one.
  const abi = artifact.abi.filter((e) => e.type !== "constructor").map(slim);
  return `export const ${name} = ${JSON.stringify(abi, null, 2)} as const satisfies Abi;`;
});

const banner = `// Generated by scripts/gen-abi.mjs — do not edit by hand.
//
// Regenerate with \`npm run abi:gen\` after any contract change, and commit the result: this file
// is the only copy of the ABI that exists inside frontend/, which is all a Vercel build can see.
//
// Unlike the hand-written ABI this replaced, it carries the contracts' \`error\` entries, so viem
// can decode custom reverts structurally instead of regexing them out of message strings.

import type { Abi } from "viem";
`;

const outDir = join(here, "..", "lib", "abi");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "generated.ts"), `${banner}\n${blocks.join("\n\n")}\n`);

const bytes = blocks.reduce((n, b) => n + b.length, 0);
console.log(`wrote lib/abi/generated.ts — ${SOURCES.length} contracts, ${(bytes / 1024).toFixed(1)} KB`);
